In [8]:
import numpy as np
import matplotlib.pyplot as plt
import csv
import os
import pickle

In [9]:
CABLE_DELAYS = 0.65 * 2
FOLDER_NAME = '2019-01-28 15-45-44'

In [10]:
with open(os.path.join(FOLDER_NAME, 'data.pickle'), 'rb') as f:
    frequencies = pickle.load(f)
    sweeps = pickle.load(f)
    frame_time = pickle.load(f)

In [44]:
step = abs(frequencies[0] - frequencies[-1]) / len(frequencies)
front_padding_count = max(int(frequencies[0] / step), 0)

padded_data = []

while len(padded_data) < front_padding_count:
    padded_data.append(0)
padded_data.append([tmp[0][1]['data'] for tmp in sweeps])

powers_of_two = [2 ** x for x in range(16)]

for size in powers_of_two:
    if (size > len(padded_data)):
        final_size = size
        break

while len(padded_data) < final_size:
    padded_data.append(0)
    
time_domain_data = [np.fft.ifft(padded_data)]

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 [array([   23.  +81.j,    48.  +70.j,    70.  +45.j, ..., -2176.+1210.j,
         -1721.+1596.j, -1312.+1855.j]),
  array([   18.  +79.j,    47.  +67.j,    67.  +47.j, ..., -2170.+1206.j,
         -1720.+1599.j, -1309.+1855.j]),
  array([   21.  +81.j,    50.  +68.j,    69.  +44.j, ..., -2169.+1217.j,
         -1720.+1600.j, -1304.+1855.j]),
  array([   21.  +84.j,    53.  +67.j,    69.  +47.j, ..., -2166.+1218.j,
         -1714.+1605.j, -1299